version: '3'
services:
  app:
    build: .
    image: hlyangster/tts-stt-solution
    container_name: tts-stt-solution
    ports:
      - "7860:7860"
    volumes:
      - ./data:/app/data
      - ./temp:/app/temp
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
    restart: unless-stopped
